AWSTemplateFormatVersion: "2010-09-09"
Description: my awesome reminder app
Parameters:
  DeploymentBucketName:
    Type: String
  Application:
    Type: String
    Default: awesome-reminder
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod
  RegisterReminderLambdaZipFile:
    Type: String
  SendReminderLambdaZipFile:
    Type: String


Resources:
  RegisterReminderLambda:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./components/register-reminder-lambda.yml
      Parameters:
        Application: !Ref Application
        Environment: !Ref Environment
        LambdaName: register-reminder
        LambdaHandler: index.handler
        LambdaBucketName: !Ref DeploymentBucketName
        LambdaZipFile: !Ref RegisterReminderLambdaZipFile
        ReminderSchedulerTargetArn: !GetAtt ReminderSqsTarget.Outputs.QueueArn 
        ReminderSchedulerTargetRoleArn: !GetAtt SchedulerRole.Outputs.SchedulerRoleArn 
        ReminderSchedulerGroupName: !GetAtt SchedulerGroup.Outputs.SchedulerGroupName

  SendReminder:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./components/send-reminder-lambda.yml
      Parameters:
        Application: !Ref Application
        Environment: !Ref Environment
        LambdaName: send-reminder
        LambdaHandler: index.handler
        LambdaBucketName: !Ref DeploymentBucketName
        LambdaZipFile: !Ref SendReminderLambdaZipFile
        ReminderSchedulerSourceArn: !GetAtt ReminderSqsTarget.Outputs.QueueArn
        ReminderSchedulerGroupName: !GetAtt SchedulerGroup.Outputs.SchedulerGroupName


  SchedulerGroup:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./components/scheduler-group.yml
      Parameters:
        Application: !Ref Application
        Environment: !Ref Environment

  ReminderSqsTarget:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./components/reminders-queue.yml
      Parameters:
        Application: !Ref Application
        Environment: !Ref Environment

  SchedulerRole:
      Type: AWS::CloudFormation::Stack
      Properties: 
        TemplateURL: ./components/scheduler-role.yml
        Parameters:
          Application: !Ref Application
          Environment: !Ref Environment
          TargetQueueArn: !GetAtt ReminderSqsTarget.Outputs.QueueArn 

  ApiGateway:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./components/api-gateway.yml
      Parameters:
        Application: !Ref Application
        Environment: !Ref Environment
        RegisterReminderLambdaArn: !GetAtt RegisterReminderLambda.Outputs.LambdaFunctionArn



      
        