AWSTemplateFormatVersion: "2010-09-09"
Description: awesome reminder api gateway

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod
  Application:
    Type: String
  RegisterReminderLambdaArn:
    Type: String


Resources:
  AwesomeReminderApi:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: !Sub ${Application}-api-${Environment}
        ProtocolType: HTTP
        CorsConfiguration:
          AllowHeaders:
            - Authorization
          AllowMethods:
            - GET
            - OPTIONS
          AllowOrigins:
            - '*'

  RegisterReminderIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref AwesomeReminderApi
      Description: Reminder Api Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RegisterReminderLambdaArn}/invocations
      IntegrationMethod: POST
      PayloadFormatVersion: '2.0'

  RegisterReminderRoute:
    Type: AWS::ApiGatewayV2::Route
    DependsOn:
      - RegisterReminderIntegration
    Properties:
      ApiId: !Ref AwesomeReminderApi
      RouteKey: 'POST /reminder'
      Target: !Join
        - /
        - - integrations
          - !Ref RegisterReminderIntegration

  AwesomeReminderDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - RegisterReminderRoute
    Properties:
      ApiId: !Ref AwesomeReminderApi

  V1Stage:
    Type: AWS::ApiGatewayV2::Stage
    DependsOn:
      - AwesomeReminderApi
      - AwesomeReminderDeployment
    Properties:
      StageName: v1
      AutoDeploy: true
      Description: v1 Stage
      DeploymentId: !Ref AwesomeReminderDeployment
      ApiId: !Ref AwesomeReminderApi

  ApiGatewayInvokePermissionForRegisterReminderLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref RegisterReminderLambdaArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AwesomeReminderApi}/*'