AWSTemplateFormatVersion: "2010-09-09"
Description: scheduler-group
Parameters:
  Application:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod

Resources:
  ScheduleGroup:
    Type: AWS::Scheduler::ScheduleGroup
    Properties: 
      Name: !Sub ${Application}-${Environment}

Outputs:
  SchedulerGroupName:
    Description: Schedule group name
    Value: !Sub ${Application}-${Environment}
    Export:
      Name: !Sub ${AWS::StackName}-schedule-group-name
